local root = assert(arg[1], "usage: embed.lua <source-root> <output.c>")
local outfile = assert(arg[2], "usage: embed.lua <source-root> <output.c>")

root = root:gsub("/+$", "")

local function dirname(p)  return (p:gsub("/[^/]*$", "")) end
local function basename(p) return (p:gsub(".*/", ""))     end

local function isfile(p)
	local f = io.open(p, "rb")
	if f then f:close() return true end
	return false
end

local function readfile(p)
	local f = assert(io.open(p, "rb"), "cannot open " .. p)
	local s = f:read("*a")
	f:close()
	return s
end

local function discoverManifests()
	local list = {}
	local pipe = assert(io.popen('find "' .. root .. '" -name _manifest.lua -type f 2>/dev/null'))
	for line in pipe:lines() do
		local rel = line:sub(#root + 2)
		local skip = rel:match("^contrib/") or rel:match("^website/")
			or rel:match("^binmodules/") or rel:match("/tests/")
			or rel:match("^packages/")
		if not skip then
			table.insert(list, rel)
		end
	end
	pipe:close()
	table.sort(list)
	return list
end

-- Collect { name: , data: } for every script.
local scripts = {}
local natives = {}

local function addScript(name, data)
	table.insert(scripts, { name = name, data = data })
end

for _, manifestRel in ipairs(discoverManifests()) do
	local manifestDir = dirname(manifestRel)
	local moduleName = basename(manifestDir)
	local baseDir = dirname(manifestDir)

	if manifestDir == manifestRel then manifestDir = "." end

	local files = dofile(root .. "/" .. manifestRel)
	for _, f in ipairs(files) do
		local full = manifestDir .. "/" .. f

		-- name relative to baseDir
		local name
		if baseDir == "." or baseDir == "" then
			name = full
		else
			name = full:sub(#baseDir + 2)
		end

		addScript(name, readfile(root .. "/" .. full))
	end

	if moduleName ~= "src" then
		local nativeFile = root .. "/" .. manifestDir .. "/native/" .. moduleName .. ".c"
		if isfile(nativeFile) then
			table.insert(natives, moduleName:gsub("^%l", string.upper))
		end
	end
end

addScript("src/_premake_main.lua", readfile(root .. "/src/_premake_main.lua"))
addScript("src/_manifest.lua", readfile(root .. "/src/_manifest.lua"))
addScript("src/_modules.lua", readfile(root .. "/src/_modules.lua"))

table.sort(scripts, function(a, b) return a.name < b.name end)

local out = assert(io.open(outfile, "wb"))
out:write("/* Auto-generated by cmake/embed.lua; any edits will be overwritten by future builds */\n")
out:write('#include "host/premake.h"\n\n')

for i, s in ipairs(scripts) do
	s.symbol = "builtin_script_" .. i
	out:write("/* " .. s.name .. " */\n")
	out:write("static const unsigned char " .. s.symbol .. "[] = {")

	local data = s.data
	for j = 1, #data do
		if (j - 1) % 32 == 0 then out:write("\n") end
		out:write(string.format("%d,", data:byte(j)))
	end

	out:write("\n};\n\n")
end

out:write("const buildin_mapping builtin_scripts[] = {\n")
for _, s in ipairs(scripts) do
	out:write(string.format('\t{"%s", %s, sizeof(%s)},\n', s.name, s.symbol, s.symbol))
end
out:write("\t{NULL, NULL, 0}\n};\n\n")

for _, n in ipairs(natives) do
	out:write("extern void register" .. n .. "(lua_State* L);\n")
end

out:write("\nvoid registerModules(lua_State* L)\n{\n\t(void)(L);\n")
for _, n in ipairs(natives) do
	out:write("\tregister" .. n .. "(L);\n")
end

out:write("}\n")
out:close()

io.write(string.format("embed.lua: wrote %d scripts to %s\n", #scripts, outfile))
